# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3ad29de
_src_path: gh:scipp/copier_template
description: Diffraction data reduction for the European Spallation Source
max_python: '3.11'
min_python: '3.8'
namespace_package: ''
nightly_deps: scipp,scippnexus,sciline,plopp,scippneutron
orgname: scipp
prettyname: Essdiffraction
projectname: essdiffraction
related_projects: Scipp,ScippNexus,ScippNeutron,Sciline,Plopp
year: 2023
